// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StorybookCabinPOCBlazor.Models;

public partial class Credit
{
    public int Id { get; set; }

    public bool Active { get; set; }

    public int UserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual User User { get; set; }
}