// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StorybookCabinPOCBlazor.Models;

public partial class User
{
    public int Id { get; set; }

    public string DisplayName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string IdentityProvider { get; set; }

    public string AuthenticationType { get; set; }

    public string Objectidentifier { get; set; }

    public string SigninMethod { get; set; }

    public string LastIpaddress { get; set; }

    public int LastAuthTime { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string LastidpAccessToken { get; set; }

    public bool IsSuperUser { get; set; }

    public virtual ICollection<Credit> Credits { get; set; } = new List<Credit>();

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();
}